Use MaybeUninit in rusage struct initialization
struct rusage hase extra fields on some platforms (e.g., when
compiling with MUSL libc to get fully static binaries), which results
in the following error message:

```
error[E0063]: missing field `__reserved` in initializer of `libc::unix::rusage`
 --> src/time.rs:6:23
  |
6 |     let mut r_usage = rusage {
  |                       ^^^^^^ missing `__reserved`

```

As kernel is supposed to fill all the fields in struct rusage, it
is safe to use MaybeUninit instead of specifying initial values of all
the fields.

It also results in shorter, simpler code.

I tested this change with my benchmarks and couldn't find any
regressions.